name: ann-bank-customer-churn-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.45=h1aa0949_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh145f28c_0
  - python=3.13.9=hc97d973_101_cp313
  - python_abi=3.13=8_cp313
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_ha0e22de_103
  - uv=0.9.9=h76e24b7_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - altair==5.5.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.0
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - executing==2.2.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.14.0
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - keras==3.12.0
      - keras-nightly==3.12.0.dev2025100703
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - namex==0.1.0
      - narwhals==2.11.0
      - nest-asyncio==1.6.0
      - numpy==2.3.4
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.16.0.29
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.28.9
      - nvidia-nvjitlink-cu12==12.9.86
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.28.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - setuptools==80.9.0
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - streamlit==1.51.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tornado==6.5.2
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - watchdog==6.0.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wheel==0.45.1
      - wrapt==2.0.1
prefix: /home/iceyisaak/anaconda3/envs/ann-bank-customer-churn-prediction
